version: "3"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  eventservicedb:
    image: mongo

  bookingservicedb:
    image: mongo

  eventservice:
    build: ./eventservice
    ports:
      - "8181:8181"
    environment:
      - AMQP_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      - MONGODB_URL=mongodb://eventservicedb/events

  bookingservice:
    build: ./bookingservice
    ports:
      - "8282:8282"
    environment:
      - AMQP_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      - MONGODB_URL=mongodb://bookingservicedb/bookings

  frontend: 
    build: ./frontend
    ports: 
      - "80:80"