version: "3"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  eventservicedb:
    image: mongo

  bookingservicedb:
    image: mongo

  eventservice:
    build: ./eventservice
    ports:
      - "8181:8181"
    env_file:
      - ./eventservice/.env

  bookingservice:
    build: ./bookingservice
    ports:
      - "8282:8282"
    env_file:
      - ./bookingservice/.env

  frontend: 
    build: ./frontend
    ports: 
      - "80:80"
    env_file:
      - ./frontend/.env
